config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  resources :places
  resources :users, except: :show do
    collection do
      post :recreate
    end
    member do
      get :reset_password
    end
  end
  
  resources :change_logs
  resources :participants, only: :index
  
  resources :events do
    member do
      get :new_import
      post :import
      get :report_detail
      get :report_general
      get :report_composition
      get :report_payment_methods
      post :duplicate
    end
    resources :modalities do
      member do
        get :admin_modalities
        post :assign_modality
        get :remove_modality
      end
    end
    resources :places do
      member do
        get :remove
        get :assign
      end
    end
    resources :participants do
      member do
        get :next_deposit_state
      end
      collection do
        get 'send_suscription_mail'
      end
      resources :air_tickets
      resources :payments
      resources :stays
    end
  end
  
  resources :bookings do
    member do
      get :next_deposit_state
    end
    resources :payments
  end
  
  resources :beds
  resources :rooms
  resources :locations do
    collection do
      get 'calendar'
    end
  end
  resources :houses
  resources :guests do
    member do
      get 'auto_edit'
      post 'auto_update'
    end
    collection do
      get 'not_access_allowed'
      get 'auto_update_success'
    end
  end
  
  namespace :reports do
    resources :bookings, only: [:index] do
      collection do
        get 'monthly_guests'
      end
    end
  end
  

  root 'bookings#index'

end

app/models/participant.rb
# == Schema Information
#
# Table name: participants
#
#  id            :integer          not null, primary key
#  guest_id      :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  deposit_state :string           default("pending")
#
class Participant < ApplicationRecord
  
  acts_as_paranoid

  belongs_to :guest
  
  has_many :participant_spaces, dependent: :destroy
  accepts_nested_attributes_for :participant_spaces, :allow_destroy => true
  
  has_many :spaces, through: :participant_spaces
  has_one :air_ticket, dependent: :destroy
  has_many :payments, as: :payable, dependent: :destroy
  has_many :stays, dependent: :destroy
  has_and_belongs_to_many :bookings, join_table: :participants_bookings
  has_many :change_logs, as: :logable, dependent: :destroy
  attr_accessor :author_id
  
  validates_presence_of :guest
  
  before_destroy { bookings.clear }
  after_create :add_create_log
  before_destroy :add_destroy_log, prepend: true
  
  scope :by_modality, ->(modality_id) { joins(:spaces).where('spaces.modality_id = ?', modality_id) }
  scope :by_space, ->(space_id) { where('participant_spaces.space_id = ?', space_id) }
  scope :by_guest, ->(guest_id) { where( guest_id: guest_id ) }
  scope :by_country, ->(country) { joins(:guest).where('guests.country': country) }
  scope :by_outside, ->(outside) { joins(:guest).where('guests.outside': outside) }
  scope :after_date, ->(date) { joins(spaces: {modality: :event}).merge(Event.after_date(date)).distinct }
  
  scope :by_international, -> (is_international) {
    is_international = is_international.to_i == 0 ? false : true
    joins(spaces: {place: :events}).merge(Event.by_international(is_international))
  }
  
  scope :by_confirmed, -> (is_confirmed) {
    if is_confirmed.to_i == 0
      joins('LEFT OUTER JOIN air_tickets ON participants.id = air_tickets.participant_id').joins('LEFT OUTER JOIN payments ON participants.id = payments.payable_id').where('air_tickets.participant_id IS NOT NULL OR (payments.payable_id IS NOT NULL AND payments.payable_type = ?)', 'Participant')
    elsif is_confirmed.to_i == 1
      joins('LEFT OUTER JOIN air_tickets ON participants.id = air_tickets.participant_id').joins('LEFT OUTER JOIN payments ON participants.id = payments.payable_id').where('air_tickets.participant_id IS NULL AND (payments.payable_id IS NULL AND payments.payable_type = ?)', 'Participant')
    end
  }
  
  delegate :display_spaces_amount, :display_stays_amount, :display_payments_amount, :display_due_spaces, :display_due_stays, :display_due, :display_stays_dates, :display_payments_method, to: :decorator
  
  # Using decorators
  def decorator
    @decorator ||= ParticipantDecorator.new(self)
  end
  
  [:given, :refunded, :pending].each do |name|
    define_method "deposit_#{name}" do
			self.deposit_state = "#{name}"
		end
		
		define_method "deposit_#{name}?" do
			self.deposit_state == "#{name}"
		end
  end
    
  def confirmed?
    air_ticket || !payments.empty?
  end
  
  def display_confirmed
    confirmed? ? "Si" : "No"
  end
  
  def to_s
    "#{guest} - #{spaces_to_s}"
  end
  
  def stays_days
    stays.sum("date_part('day', age(end_at, start_at))").to_i
  end
  
  def stays_amount
    stays.sum("amount * date_part('day', age(end_at, start_at))")
  end
  
  def payments_amount
    payments.sum("amount")
  end
  
  def spaces_amount
    spaces.sum("amount")
  end
  
  def payments_spaces
    payments.where(reason: 'Evento').sum("amount")
  end
  
  def payments_stays
    payments.where(reason: 'Estadia').sum("amount")
  end
  
  def due_spaces
    spaces_amount - payments_spaces
  end
  
  def due_stays
    stays_amount - payments_stays
  end
  
  def due
    due_spaces + due_stays
  end
  
  def next_deposit_state_action
    if deposit_pending?
      return 'Depósito Abonado'
    elsif deposit_given?
      return 'Depósito Reembolsado'
    elsif deposit_refunded?
      return 'Reiniciar a Pendiente'
    end
  end
  
  def next_deposit_state
    if deposit_pending?
      deposit_given
    elsif deposit_given?
      deposit_refunded
    elsif deposit_refunded?
      deposit_pending
    end
  end
  
  def spaces_to_s
    to_s = ''
    spaces.each do |space|
      to_s += space.to_s + "<br>"
    end
    to_s.html_safe
  end
  
  def modalities_start_at
    spaces.joins(:modality).order("modalities.start_at ASC").first.modality.start_at
  end
  
  def modalities_end_at
    return spaces.joins(:modality).order("modalities.end_at DESC").first.modality.end_at
  end
  
  def add_create_log
    change_logs.create(change: "creó al participante #{to_s}", author_id: author_id)
  end

  def add_destroy_log
    change_log = spaces.first.modality.event.change_logs.new(change: "eliminó al participante #{to_s}", author_id: author_id)
    change_log.is_reviewed = false if confirmed?
    change_log.save
  end

  def show_path
    Rails.application.routes.url_helpers.event_participant_path(spaces.first.modality.event, self)
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < BaseEventController
	
	respond_to :js, :only => :index
	
	before_action :set_event, :if => proc {params.has_key?(:event_id)}
	before_action :set_author, only: :destroy
	before_action :send_modalities, only: [:edit, :new, :index],  :if => proc {params.has_key?(:event_id)} 
	
	has_scope :by_modality, :by_space, :by_guest, :by_confirmed, :after_date
	has_scope :by_international
	
	def create
		create!(notice: "Participante creado exitosamente") { event_participants_path(@event) }
	end
	
	def index
		if params.has_key?(:event_id)
			@participants = User.participants_by_role(current_user, @event)
		else 
			@participants = Participant.all
		end
		@participants = apply_scopes(@participants).page(params[:page])
		respond_to do |format|
			format.html
    		format.js {render layout: false, content_type: 'text/javascript'}
		end
	end
	
	def destroy
		destroy! do |format|
			format.html { redirect_back(fallback_location: root_path) }
		end
	end
	
	def next_deposit_state
		@participant = Participant.find(params[:id])
		@participant.next_deposit_state
		@participant.save!
		redirect_to event_participant_path(@event, @participant)
	end
	
	def send_suscription_mail
		@participants = apply_scopes(@event.participants)
		@participants.each do |participant|
			puts "Token for " + participant.guest.email
			tokenControl = TokenControl.where(guest: participant.guest).first
			tokenControl = TokenControl.create(guest: participant.guest, auth_token: generate_auth_token) if not tokenControl
			if tokenControl.state == 'pending'
				puts 'Sending email'
				GuestMailer.suscription(participant.guest, tokenControl.auth_token).deliver!
				tokenControl.state = 'sent'
				tokenControl.save
				puts 'Email sent and record changed state to sent'
			end
		end
		redirect_to event_participants_path(@event)
	end
	
	def update
		update! { event_participant_path(@event, @participant) }
	end
	
	def show
		@participant = resource
		@bookings = Kaminari.paginate_array(@participant.bookings).page(params[:page])
		@changes = Kaminari.paginate_array(@participant.change_logs.order(created_at: :desc)).page(params[:change_page])
	end
	
	private

		def participant_params
			params.require(:participant).permit(:guest_id, :space_id, :author_id, participant_spaces_attributes: [:id, :participant_id, :space_id, :note, :author_id, :_destroy])
		end
		
		def set_event
			@event = Event.find(params[:event_id])
		end
		
		def send_modalities
			@modalities = @event.modalities.includes(:spaces)
			gon.jbuilder "app/views/modalities/index.json.jbuilder", as: "modalities"
		end
		
		def collection
			@event.participants
		end
		
		def generate_auth_token
			SecureRandom.uuid.gsub(/\-/,'')
		end
		
		def set_author
    		resource.author_id = current_user.id
    	end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.slim
= nested_form_for [@event, @participant] do |f|
  = render "layouts/error_messages", :target => @participant
  .row
    .col-sm-9.col-md-5
      .form-group
        = f.label :guest_id, "Contacto", class: "control-label"
        .input-group
          = f.text_field :guest_id, :data => {:guest => @participant.guest}
          span#clean-guest-input-btn.input-group-btn class=(action_name == 'edit' ? 'invisible' : '')
            button.btn.btn-default[type="button"] X
  h4 Modalidades
  = f.fields_for :participant_spaces do |builder|
    .row
      = builder.hidden_field :author_id, value: current_user.id
      .col-lg-3
        .form-group
          .form-label
            label.control-label Modalidad
          .form-wrapper
            = select_tag :modality_id, options_for_select(@event.modalities.pluck(:name, :id), builder.object.nil? || builder.object.space.nil? ? nil : builder.object.space.modality.id), class: "form-control modality_select", include_blank: true, required: true
      .col-lg-3
        .form-group
          .form-label
            label.control-label Categoría
          .form-wrapper
            = builder.select :space_id, (builder.object.nil? || builder.object.space.nil? ? [] : options_for_select(builder.object.space.modality.spaces.joins(:place).pluck(Arel.sql("places.name || ' (' || spaces.amount || ' USD)'"), "spaces.id"), builder.object.space.id)), {}, {class: "form-control space_select", include_blank: true, required: true}
      .col-lg-3  
        .form-group
          .form-label
            label.control-label Observaciones
          .form-wrapper
            = builder.text_field :note, class: "form-control"
      .col-lg-3
        .form-group
          .form-label.invisible.control-label eliminar
          div= builder.link_to_remove "Eliminar", class: "btn btn-danger"
    
    br
    
  = f.link_to_add "Adicionar modalidad", :participant_spaces, class: "btn btn-sm btn-default"
  
  br
  br
  br
  = f.submit nil, :class => 'btn btn-primary'

app/views/participants/_list.html.slim
table.table
  thead
    tr
      th Participante
      th Participación
      th Confirmado 
      th
      th

  tbody
    - @participants.each do |participant|
      tr
        td = participant.guest
        td = participant.spaces_to_s
        td = participant.display_confirmed
        td
          - if @event.present?
            .btn-group
              button.btn.btn-default.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button" 
                | Acciones
                span.caret
              ul.dropdown-menu
                  li = link_to 'Ver Detalles', [@event, participant]
                  - if can? :manage, Participant
                    li = link_to 'Cambiar participación', edit_event_participant_path(@event, participant)
                    li = link_to 'Eliminar', [@event, participant], data: {:confirm => '¿Estás seguro de eliminar este participante?'}, :method => :delete
          - else
            = link_to 'Ver Detalles', [participant.spaces.first.modality.event, participant], class: "btn btn-default"
        
        
= paginate @participants, remote: true

app/views/participants/edit.html.slim
h1 Editing participant

== render 'form'
br
= link_to 'Vovler', event_participants_path(@event), class: "btn btn-default"

app/views/participants/index.html.slim
.page-header
	h1 Lista de Participantes
	- if can? :manage, Participant
	  = link_to 'Nuevo Participante', new_event_participant_path(@event), class: "btn btn-primary btn-header"
    |&nbsp;
	- if current_user.admin?
	  = link_to 'Importar participantes', new_import_event_path(@event), class: "btn btn-primary btn-header"
	  //= link_to 'Enviar link de suscripción', send_suscription_mail_event_participants_path({event_id: @event.id}.merge(<)), class: "btn, btn-primary btn-header"
h2 Buscar Por
= form_tag event_participants_path, method: :get do
  .row
    .form-group.col-lg-3
      = label_tag :by_guest, "Contacto", class: "control-label"
      .input-group
        = text_field_tag :by_guest, nil, :data => {:guest => (params[:by_guest] && !params[:by_guest].blank?) ? Guest.find(params[:by_guest]) : "" }, class: "form-control"
        span#clean-guest-btn.input-group-btn
          button.btn.btn-default[type="button"] X
    .form-group.col-lg-3
      = label_tag :by_modality, "Modalidad", class: "control-label"
      = select_tag :by_modality, options_for_select(@event.modalities.pluck(:name, :id), params[:by_modality]), include_blank: true, class: "form-control"
    .form-group.col-lg-3
      = label_tag :by_space, "Categoría", class: "control-label"
      = select_tag :by_space, nil, include_blank: true, class: "form-control", disabled: :disabled, :data => { :space => params[:by_space] }
    .form-group.col-lg-2
      = label_tag :by_confirmed, "Confirmado", class: "control-label"
      = select_tag :by_confirmed, options_for_select([["Si", 0], ["No", 1]], params[:by_confirmed]), include_blank: true, class: "form-control"
    .form-group.col-lg-1
      = label_tag :by_con, nil, class: "control-label invisible"
      = submit_tag "Buscar", class: "btn btn-primary"
br
br

#participant_content
  = render "list"

app/views/participants/index.js.erb
$("#participant_content").html("<%= j(render 'list', changes: @change_logs, remote: true) %>");

app/views/participants/new.html.slim
h1 Nuevo Participante

== render 'form'

br
br

= link_to 'Volver', event_participants_path(@event), class: "btn btn-default"

app/views/participants/show.html.slim
.page-header
	h4= @participant.guest
	- if can? :manage, Modality
	  = link_to 'Información personal', edit_guest_path(@participant.guest), class: "btn btn-default btn-header btn-xs small-link"
	  |&nbsp;
	= link_to 'Solicitar revisión de reservas', change_logs_path(change_log: {is_reviewed: 0, logable_id: @participant.id, logable_type: 'Participant', change: "solicita revisión de cambios", author_id: current_user.id}), method: :post, class: "btn btn-xs small-link btn-primary btn-header"
	

div
  ul#navigation.nav.nav-tabs role="tablist"
    li.active role="presentation"
      a href="#details" aria-controls="details" role="tab" data-toggle="tab"
        | Detalles
    li role="presentation"
      a href="#bookings" aria-controls="bookings" role="tab" data-toggle="tab"
        | Reservas
    li role="presentation"
      a href="#changes" aria-controls="changes" role="tab" data-toggle="tab"
        | Cambios
  .tab-content
    #details.participant-body.tab-pane.active
      br
      - if not @event.international?
        h5.table-title Información del viaje
        |&nbsp;
        - if @participant.air_ticket.nil?
          - if can? :manage, AirTicket
            = link_to "Adicionar Boleto Aereo", new_event_participant_air_ticket_path(@event, @participant), class: 'btn btn-primary btn-xs'
          br
          br
        - if not @participant.air_ticket.nil?
          table.table.table-actions
            thead
              tr
                th Llega el
                th Sale el
                th Llega a
                th Sale desde
                th Llegada estimada a Cuenca
                th
                th
            tr
              td= l @participant.air_ticket.arrive_at
              td= l @participant.air_ticket.leave_at
              td= @participant.air_ticket.arrive_to
              td= @participant.air_ticket.leave_from
              td= l @participant.air_ticket.estimated_at
              td.actions
                - if can? :manage, AirTicket
                  = link_to "Editar", edit_event_participant_air_ticket_path(@event, @participant, @participant.air_ticket), class: "btn btn-xs btn-default"
                  |&nbsp;
                  = link_to "Eliminar", [@event, @participant, @participant.air_ticket], method: :delete, data: {confirm: "Estás seguro de eliminar este boleto aereo"}, class: "btn btn-xs btn-danger"
        br
        br
      
      h5.table-title Modalidades
      |&nbsp;
      - if can? :manage, Participant
        = link_to "Modificar Modalidades", edit_event_participant_path(@event, @participant), class: "btn btn-primary btn-xs"
      br
      
      table.table.table-actions
        thead
          tr
            th Modalidad
            th Desde el
            th Hasta el
            th Valor
            th Observaciones
        tbody
          - @participant.participant_spaces.each do |participant_space|
            tr
              td= participant_space.space.to_s_wihtout_amount
              td= l participant_space.space.modality.start_at, format: :date
              td= l participant_space.space.modality.end_at, format: :date
              td= to_currency participant_space.space.amount
              td= participant_space.note
      
      br
      br
      
      - if not @event.international?
        h5.table-title Estadías
        |&nbsp;
        - if can? :manage, Stay
          = link_to "Adicionar Estadía", new_event_participant_stay_path(@event, @participant), class: 'btn btn-primary btn-xs'
        br
        table.table.table-actions
          thead
            tr
              th 
              th Espacio
              th Desde el
              th Hasta el
              th Valor total
              th
              th
          - @participant.stays.order(:start_at).each do |stay|
            tr
              td
                b= stay.when_to_s
              td= stay.place
              td= l stay.start_at, format: :date
              td= l stay.end_at, format: :date
              td= stay.display_detailed_total_amount
              td
                - if can? :manage, Stay
                  = link_to "Editar", edit_event_participant_stay_path(@event, @participant, stay), class: "btn btn-xs btn-default"
                  |&nbsp;
                  = link_to "Eliminar", [@event, @participant, stay], method: :delete, data: {confirm: "Estás seguro de eliminar esta estadía"}, class: "btn btn-xs btn-danger"
        
        br
        br
      
      h5.table-title Pagos
      |&nbsp;
      - if can? :manage, Payment
        = link_to "Adicionar Pago", new_event_participant_payment_path(@event, @participant), class: 'btn btn-primary btn-xs'
      br
      table.table.table-actions
        thead
          tr
            th Pagado el
            th Valor
            th Medio
            th Razón
            th Descripción
            th
            th
        - @participant.payments.each do |payment|
          tr
            td= l payment.paid_at, format: :date
            td= to_currency payment.amount
            td= payment.method
            td= payment.reason
            td= payment.description
            td.actions
              - if can? :manage, Payment
                = link_to "Editar", edit_event_participant_payment_path(@event, @participant, payment), class: "btn btn-xs btn-default"
                |&nbsp;
                = link_to "Eliminar", [@event, @participant, payment], method: :delete, data: {confirm: "Estás seguro de eliminar este pago"}, class: "btn btn-xs btn-danger"
      
      br
      br
      
      - if not @event.international?
        h5.table-title
          = "Depósito de seguridad por #{to_currency @event.deposit_amount}"
          |&nbsp;
          |&nbsp;
          |&nbsp;
          |&nbsp;
          span class=("deposit-state #{@participant.deposit_state}")
            = t("participant.deposit.state.#{@participant.deposit_state}")
        |&nbsp;
        |&nbsp;
        - if can? :manage, Participant
          = link_to @participant.next_deposit_state_action, next_deposit_state_event_participant_path(@event, @participant), class: "btn btn-primary btn-xs"
      
        br
        br
        
      br
      .row
        .col-md-offset-2.col-md-8
          table.table.summary-table
            thead
              tr
                th
                  h5.table-title Resumen de un vistazo
                th
            tr.subheader
              td Modalidades
              td 
            tr
              td Total Modalidades
              td= to_currency @participant.spaces_amount
            tr.payment
              td Pago Modalidades
              td= to_currency  @participant.payments_spaces
            - if not @event.international?
              tr.subtotal
                td
                td= "Subtotal #{to_currency @participant.due_spaces}"
              tr.subheader
                td Estadías
                td 
              tr
                td Total Estadías
                td= to_currency @participant.stays_amount
              tr.payment
                td Pago Estadías
                td= to_currency @participant.payments_stays
              tr.subtotal
                td
                td= "Subtotal #{to_currency @participant.due_stays}"
            tr.total-due
              td
                b Total
              td
                b= to_currency @participant.due
      
      = link_to 'Volver', event_participants_path(@event), class: "btn btn-default"
      
      br
      br
    
    #bookings.tab-pane
      br
      h5.table-title Reservas
      |&nbsp;
      - if can? :manage, Booking
        = link_to "Adicionar Reserva", new_booking_path(booking: {guest_id: @participant.guest_id}, participant_id: @participant.id, back_url: "#{url_for([@event, @participant])}#bookings"), class: 'btn btn-primary btn-xs'
      = render 'bookings/list', {bookings: @bookings}
    #changes.tab-pane
      br
      h5.table-title Cambios
      br
      br
      = form_tag change_logs_path, method: :get, "data-type": "script", remote: true do
        .row
          = hidden_field_tag "logable_types[]", "Participant"
          = hidden_field_tag "logable_ids[]", @participant.id
          .col.col-xs-12.col-md-2
            = label_tag "Revisado?"
            = select_tag :was_reviewed, options_for_select([['Pendiente Revisión', 0],['Revisados', 1], ['Todos', 2]], params[:was_reviewed]), class: 'form-control'
          .col.col-xs-12.col-md-3
            = label_tag "Realizado Desde"
            = text_field_tag "created_at[started_at]", nil, class: "datepicker start-datepicker form-control", :data => {"end-datepicker": "#created_at_finished_at", "hidden-datepicker": "#hidden_created_at_started_at"}
            = hidden_field_tag "created_at[started_at]", (params.has_key?(:created_at) && params[:created_at].has_key?(:started_at) ? params[:created_at][:started_at] : nil), id: "hidden_created_at_started_at", class: "hidden_field_date", :data => {"date-field": "#created_at_started_at"}
          .col.col-xs-12.col-md-3
            = label_tag "Realizado Hasta"
            = text_field_tag "created_at[finished_at]", nil, class: "datepicker form-control", :data => {"hidden-datepicker": "#hidden_created_at_finished_at"}
            = hidden_field_tag "created_at[finished_at]", (params.has_key?(:created_at) && params[:created_at].has_key?(:finished_at) ? params[:created_at][:finished_at] : nil), id: "hidden_created_at_finished_at", class: "hidden_field_date", :data => {"date-field": "#created_at_finished_at"}
          .col.col-xs-12.col-md-1
            = label_tag "Filtrar", "FiltrarFiltrar", class: "invisible"
            = submit_tag "Filtrar", class: "btn btn-primary remote-change"
      br
      #change_log_content