config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  resources :places
  resources :users, except: :show do
    collection do
      post :recreate
    end
    member do
      get :reset_password
    end
  end
  
  resources :change_logs
  resources :participants, only: :index
  
  resources :events do
    member do
      get :new_import
      post :import
      get :report_detail
      get :report_general
      get :report_composition
      get :report_payment_methods
      post :duplicate
    end
    resources :modalities do
      member do
        get :admin_modalities
        post :assign_modality
        get :remove_modality
      end
    end
    resources :places do
      member do
        get :remove
        get :assign
      end
    end
    resources :participants do
      member do
        get :next_deposit_state
      end
      collection do
        get 'send_suscription_mail'
      end
      resources :air_tickets
      resources :payments
      resources :stays
    end
  end
  
  resources :bookings do
    member do
      get :next_deposit_state
    end
    resources :payments
  end
  
  resources :beds
  resources :rooms
  resources :locations do
    collection do
      get 'calendar'
    end
  end
  resources :houses
  resources :guests do
    member do
      get 'auto_edit'
      post 'auto_update'
    end
    collection do
      get 'not_access_allowed'
      get 'auto_update_success'
    end
  end
  
  namespace :reports do
    resources :bookings, only: [:index] do
      collection do
        get 'monthly_guests'
      end
    end
  end
  

  root 'bookings#index'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id             :integer          not null, primary key
#  name           :string
#  start_at       :date
#  end_at         :date
#  active         :boolean
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  deposit_amount :decimal(, )      default(0.0)
#  international  :boolean          default(FALSE)
#
class Event < ApplicationRecord
    
    acts_as_paranoid

    has_many :modalities, dependent: :destroy
    has_and_belongs_to_many :places,  :join_table => :places_events
    has_many :change_logs, as: :logable, dependent: :destroy
    attr_accessor :author_id
    
    delegate :display_deposit_amount, to: :decorator

    before_destroy { places.clear }

    scope :after_date, -> (date) { where("events.end_at >= ?", date) }
    scope :by_international, -> (is_international) { where(international: is_international) }
    
    # Using decorators
    def decorator
        @decorator ||= EventDecorator.new(self)
    end
    
    def participants
        Participant.joins(spaces: :modality).where("modalities.event_id = ?", id).select("DISTINCT(participants.id), participants.guest_id")
    end
    
    def to_s
        name
    end
    
    def spaces_amount
        Space.joins([:participants, :modality]).where("modalities.event_id = ?").sum("spaces.amount")
    end
    
    def stays_amount
        Space.joins(participants: :stays).joins(:modality).where("modalities.event_id = ?").sum("stays.amount * date_part('day', age(stays.end_at, stays.start_at))")
    end
    
    def payments_spaces
        Space.joins(participants: :payments).joins(:modality).where("modalities.event_id = ?").where("payments.reason = ?", "Evento").sum("payments.amount")
    end
    
    def payments_stays
        Space.joins(participants: :payments).joins(:modality).where("modalities.event_id = ?").where("payments.reason = ?", "Estadia").sum("payments.amount")
    end
    
    def due_spaces
        payments_spaces - spaces_amount
    end
    
    def due_stays
        payments_stays - stays_amount
    end
end

app/controllers/events_controller.rb
class EventsController < BaseEventController
  
  custom_actions :resource => [:new_import, :report_composition]
  
  require 'csv'
  
  def create
    create! { events_path }
  end
  
  def update
    update! { events_path }
  end
  
  def import
    @event = Event.find params[:id]
    csv_file = params[:file]
    puts 'INICIO ------------------------:   '
    CSV.foreach(csv_file.path, :headers => true, :col_sep => ';', encoding:'iso-8859-1:utf-8') do |row|
      guest = Guest.where(email: row['email']).first
      if not guest
        guest = Guest.new(email: row['email'])
        puts 'Creando nuevo contacto en importacion con email: ' + row['email']
      end
      guest.name = row['name']
      guest.surname = row['surname']
      guest.age = row['age']
      guest.city = row['city']
      guest.city = row['country']
      guest.city = row['phone_number']
      guest.save
      puts 'Contacto guardado: ' + row['email']
      modality = @event.modalities.where(name: row['modality']).first
      puts 'La modalidad: ' + row['modality'] + ' si fue encontrada'
      space = modality.spaces.joins(:place).where("places.name = ?", row['space']).first
      puts 'El espacio: ' + row['space'] + ' si fue encontrado'
      participant = Participant.create(guest: guest, space: space)
      if participant
        puts 'El participante ' + participant.id.to_s + " se ha importado correctamente"
      else
        puts 'No se pudo importar al participante ' + participant.id.to_s + ' porque ' + participant.errors.full_messages
      end
    end
  end
  
  def report_detail
    @participants = User.participants_by_role(current_user, Event.find(params[:id]))
    @by = params[:by]
    respond_to do |format|
			format.xlsx {
				response.headers['Content-Disposition'] = "attachment; filename=\" Detalle #{DateTime.now.strftime('%Y %m %d')}.xlsx\""
			}
			format.html
		end
  end
  
  def report_composition
    @participants = User.participants_by_role(current_user, resource)
    respond_to do |format|
			format.xlsx {
				response.headers['Content-Disposition'] = "attachment; filename=\"Detalle por modalidades separadas #{DateTime.now.strftime('%Y %m %d')}.xlsx\""
			}
			format.html
		end
  end
  
  def report_payment_methods
    @participants = User.participants_by_role(current_user, resource)
    respond_to do |format|
			format.xlsx {
				response.headers['Content-Disposition'] = "attachment; filename=\"Pagos por modalidad #{DateTime.now.strftime('%Y %m %d')}.xlsx\""
			}
			format.html
		end
  end

  def report_general
    @event = Event.find params[:id]
    @by = params[:by]
    respond_to do |format|
			format.xlsx {
				response.headers['Content-Disposition'] = "attachment; filename=\"Occupancy of Beds #{@date_for_months.strftime('%Y')}.xlsx\""
			}
			format.html
		end
  end

  def duplicate
    ActiveRecord::Base.transaction do
      event = Event.find params[:id]
      new_event = event.dup
      new_event.name = new_event.name + " COPY"
      new_event.save
      event.modalities.each do |modality|
        new_modality = modality.dup
        new_event.modalities << new_modality
        modality.spaces.each do |space|
          new_space = space.dup
          new_modality.spaces << new_space
        end
      end
      new_event.places = event.places
    end
    redirect_to events_path
  end
  
  private
    def event_params
      params.require(:event).permit(:name, :start_at, :end_at, :active, :deposit_amount, :international)
    end

    def collection
			Event.all.order(start_at: :desc).page(params[:page])
		end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.slim
= bootstrap_form_for @event do |f|
  .row
    .field.col-lg-3
      = f.text_field :name
    .field.col-lg-3
      = f.text_field :start_at 
    .field.col-lg-3
      = f.text_field :end_at
    .field.col-lg-3
      = f.number_field :deposit_amount
    .field.col-lg-3
      = f.check_box :international
  
  = f.primary

app/views/events/edit.html.slim
h4= "Editar evento #{@event}"

== render 'form'

br

= link_to 'Volver', events_path, class: "btn btn-default"

app/views/events/index.html.slim
.page-header 
	h1 Lista de Eventos
	- if can? :manage, Event
		= link_to 'Nuevo Evento', new_event_path, class: "btn btn-primary btn-header"
		|&nbsp;
		= link_to "Administrar Permisos", users_path, class: "btn btn-primary btn-header" if can? :manage, User
	
br

table.table
	thead
		tr
			th Nombre
			th Empieza el
			th Termina el
			th

	tbody
		- collection.each do |event|
			- if can? :read, event
				tr
					td = event.name
					td = event.start_at
					td = event.end_at
					td
						= link_to 'Entrar', event_participants_path(event), class: "btn btn-primary btn-xs"
						- if can? :manage, Event
							|&nbsp;
							|&nbsp;
							= link_to 'Editar', edit_event_path(event), class: "btn btn-default btn-xs"
							|&nbsp;
							|&nbsp;
							= link_to 'Eliminar', event, data: {:confirm => 'Estás seguro de eliminar este evento?'}, :method => :delete, class: "btn btn-danger btn-xs"
							|&nbsp;
							|&nbsp;
							= form_tag duplicate_event_path(event), class: "d-inline" do
								= submit_tag 'Duplicar', data: {confirm: '¿Estás seguro de duplicar este evento?'}

= paginate collection

app/views/events/new.html.slim
h1 Nuevo Evento

== render 'form'

br

= link_to 'Volver', events_path, class: "btn btn-small btn-default"

app/views/events/new_import.html.slim
h1 Importar Participantes

= form_tag import_event_path(@event), multipart: true
    = file_field_tag :file
    br
    = submit_tag "Importar"
br

= link_to 'Volver', events_path, class: "btn btn-small btn-default"

app/views/events/report_detail.html.slim
- @participants.each do |participant|
 = participant.guest.name

app/views/events/show.html.slim
p#notice = notice

p
  strong Name:
  = @event.name
p
  strong Start at:
  = @event.start_at
p
  strong End at:
  = @event.end_at
p
  strong Active:
  = @event.active

= link_to 'Edit', edit_event_path(@event)
'|
= link_to 'Back', events_path