config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  resources :places
  resources :users, except: :show do
    collection do
      post :recreate
    end
    member do
      get :reset_password
    end
  end
  
  resources :change_logs
  resources :participants, only: :index
  
  resources :events do
    member do
      get :new_import
      post :import
      get :report_detail
      get :report_general
      get :report_composition
      get :report_payment_methods
      post :duplicate
    end
    resources :modalities do
      member do
        get :admin_modalities
        post :assign_modality
        get :remove_modality
      end
    end
    resources :places do
      member do
        get :remove
        get :assign
      end
    end
    resources :participants do
      member do
        get :next_deposit_state
      end
      collection do
        get 'send_suscription_mail'
      end
      resources :air_tickets
      resources :payments
      resources :stays
    end
  end
  
  resources :bookings do
    member do
      get :next_deposit_state
    end
    resources :payments
  end
  
  resources :beds
  resources :rooms
  resources :locations do
    collection do
      get 'calendar'
    end
  end
  resources :houses
  resources :guests do
    member do
      get 'auto_edit'
      post 'auto_update'
    end
    collection do
      get 'not_access_allowed'
      get 'auto_update_success'
    end
  end
  
  namespace :reports do
    resources :bookings, only: [:index] do
      collection do
        get 'monthly_guests'
      end
    end
  end
  

  root 'bookings#index'

end

app/models/payment.rb
# == Schema Information
#
# Table name: payments
#
#  id           :integer          not null, primary key
#  paid_at      :datetime
#  amount       :decimal(, )
#  description  :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  method       :string
#  reason       :string           default("Evento")
#  payable_id   :integer
#  payable_type :string
#
class Payment < ApplicationRecord

  acts_as_paranoid
  
  belongs_to :payable, polymorphic: true
  attr_accessor :author_id
  
  after_create :add_create_log
  before_destroy :add_destroy_log
  
  after_update :add_update_log
  
  delegate :display_amount, to: :decorator
  
  PAYMENT_METHODS = ["Efectivo", "Paypal", "Banco", "Página Web", "Sede", "Otro"]
  
  def decorator
    @decorator ||= StayDecorator.new(self)
  end
  
  def add_create_log
    payable.change_logs.create(change: "creó el pago #{to_s}", author_id: author_id, is_reviewed: true)
  end
  
  def add_update_log
    payable.change_logs.create(change: "actualizó el pago  #{to_s}", author_id: author_id)
  end
  
  def add_destroy_log
    payable.change_logs.create(change: "eliminó el pago #{to_s}", author_id: author_id, is_reviewed: true)
  end
  
  def to_s
    "#{display_amount} el #{I18n.l paid_at}"
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  
  inherit_resources
  
  belongs_to :participant, :booking, polymorphic: true, optional: true
  
  before_action :set_event
  before_action :set_author, only: :destroy
  
  
  def index
    @booking = parent
    index!
  end
  
  def create
    create! { session[:previous_url] }
  end
  
  def update
    update! { session[:previous_url] }
  end
  
  def destroy
    destroy! { url_for(request.referer) }
  end
  
  def new
    session[:previous_url] = request.referer
    @payable = parent
    new!
  end
  
  def edit
    session[:previous_url] = request.referer
    @payable = parent
    edit!
  end
  
  private
  
    def payment_params
      params.require(:payment).permit(:participant_id, :paid_at, :amount, :description, :method, :reason, :author_id)
    end
    
    def set_event
      @event = Event.find(params[:event_id]) if params[:event_id]
    end
    
    def set_author
      resource.author_id = current_user.id
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.slim
= bootstrap_form_for [@event, @payable, @payment] do |f|
  = f.hidden_field :author_id, value: current_user.id
  .field.col-lg-3
    = f.text_field :paid_at, value: f.object.paid_at.nil? ? nil : l(f.object.paid_at), required: true
  .field.col-lg-3
    = f.number_field :amount, step:'any', required: true
  .field.col-lg-3
    = f.select :method, options_for_select(Payment::PAYMENT_METHODS, f.object.method.nil? ? nil : f.object.method), required: true
  - if @payable.class.name == 'Participant'
    .field.col-lg-3
      = f.select :reason, options_for_select(["Estadia", "Evento"], f.object.reason.nil? ? nil : f.object.reason), required: true
  .field.col-lg-3
    = f.text_area :description
  br
  = f.submit nil, :class => 'btn btn-primary'

app/views/payments/edit.html.slim
h1 Editar Pago

== render 'form'

br

= link_to 'Volver', url_for(:back), class: "btn btn-default"

app/views/payments/index.html.slim
.page-header
	h4
		= "Reserva de "
		= link_to "#{@booking.guest.name} #{@booking.guest.surname}", guest_path(@booking.guest), class: "record-link"

= form_for @booking, html: { class: "form form-inline booking" } do |f|
	.form-group
		.row
			.col-lg-12
				= f.label :amount, :class => 'control-label'
		= f.number_field :amount, {:class => 'form-control'}
	.form-group
		.row
			.col-lg-12
				= f.label :deposit_amount, :class => 'control-label'
		= f.number_field :deposit_amount, {:class => 'form-control'}
	.form-group
		.row
			.col-lg-12
				span.invisible action
		= f.submit nil, :class => 'btn btn-primary'

br

table.table
	thead
		tr
			th= "Ubicación"
			th= "Casa"
			th= "Cuarto"
			th= "Cama"
			th= "Empieza el"
			th= "Termina el"
			th= "Valor total"
	tbody
		tr
			td= @booking.bed.room.house.location.name
			td= @booking.bed.room.house.name
			td= @booking.bed.room.name
			td= @booking.bed.number
			td= l @booking.start_date
			td= l @booking.end_date
			td= @booking.display_detailed_total_amount
		
h5.table-title Pagos
|&nbsp;
= link_to 'Nuevo Pago', new_booking_payment_path(@booking), :class => 'btn btn-primary btn-xs'
.row
	.col-md-8
		table.table.table-actions.table-striped
			thead
				tr
					th Pagado el
					th Valor
					th Descripción
					th
		
			tbody 
				- @payments.each do |payment|
					tr
						td = l payment.paid_at, format: :date
						td = to_currency payment.amount
						td = payment.description
						td
							= link_to "Editar", edit_booking_payment_path(@booking, payment), class: "btn btn-xs btn-default"
							|&nbsp;
							= link_to "Eliminar", [@booking, payment], data: {:confirm => 'Are you sure?'}, :method => :delete, class: "btn btn-xs btn-danger"


		h5.table-title
			= "Depósito de seguridad por #{to_currency @booking.deposit_amount}"
			|&nbsp;
			|&nbsp;
			|&nbsp;
			|&nbsp;
			span class=("deposit-state #{@booking.deposit_state}")
				= t("participant.deposit.state.#{@booking.deposit_state}")
		|&nbsp;
		|&nbsp;
		= link_to @booking.next_deposit_state_action, next_deposit_state_booking_path(@booking), class: "btn btn-primary btn-xs"
		
br

.row
	.col-md-offset-2.col-md-7
		table.table.summary-table
			thead
				tr
					th
						h5.table-title Resumen
					th
			tbody
				tr
					td Total Reserva
					td= @booking.display_detailed_total_amount
				tr.payment
					td Pago Reserva
					td= @booking.display_payments_amount
				tr
					td
						b Total
					td
						b= @booking.display_due

= link_to 'Volver', bookings_path(), class: "btn btn-default"
	
br
br

app/views/payments/new.html.slim
h1 Nuevo Pago

== render 'form'

br

= link_to 'Volver', url_for(:back), class: "btn btn-default"

app/views/payments/show.html.slim
p#notice = notice

p
  strong Participant:
  = @payment.participant
p
  strong Paid at:
  = @payment.paid_at
p
  strong Amount:
  = @payment.amount
p
  strong Description:
  = @payment.description

= link_to 'Edit', edit_payment_path(@payment)
'|
= link_to 'Back', payments_path