config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  resources :places
  resources :users, except: :show do
    collection do
      post :recreate
    end
    member do
      get :reset_password
    end
  end
  
  resources :change_logs
  resources :participants, only: :index
  
  resources :events do
    member do
      get :new_import
      post :import
      get :report_detail
      get :report_general
      get :report_composition
      get :report_payment_methods
      post :duplicate
    end
    resources :modalities do
      member do
        get :admin_modalities
        post :assign_modality
        get :remove_modality
      end
    end
    resources :places do
      member do
        get :remove
        get :assign
      end
    end
    resources :participants do
      member do
        get :next_deposit_state
      end
      collection do
        get 'send_suscription_mail'
      end
      resources :air_tickets
      resources :payments
      resources :stays
    end
  end
  
  resources :bookings do
    member do
      get :next_deposit_state
    end
    resources :payments
  end
  
  resources :beds
  resources :rooms
  resources :locations do
    collection do
      get 'calendar'
    end
  end
  resources :houses
  resources :guests do
    member do
      get 'auto_edit'
      post 'auto_update'
    end
    collection do
      get 'not_access_allowed'
      get 'auto_update_success'
    end
  end
  
  namespace :reports do
    resources :bookings, only: [:index] do
      collection do
        get 'monthly_guests'
      end
    end
  end
  

  root 'bookings#index'

end

app/models/place.rb
# == Schema Information
#
# Table name: places
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Place < ApplicationRecord
    
    acts_as_paranoid

    has_many :spaces, dependent: :destroy
    has_and_belongs_to_many :events,  :join_table => :places_events
    
    def to_s
        name
    end
end

app/controllers/places_controller.rb
class PlacesController < BaseEventController
  
  belongs_to :event
  
  def index
    @place = Place.new()
    @places = Place.all.order(:name).page(params[:page])
    @own_places = parent.places.order(:name).to_a
  end
  
  def create
    Place.create(place_params)
    redirect_back(fallback_location: root_path)
  end
  
  def update
    @place = Place.find(params[:id])
    @place.update(place_params)
    redirect_to params[:back_url]
  end
  
  def edit
    @place = Place.find(params[:id])
    @back_url = request.referrer
  end
  
  def assign
    parent.places << Place.find(params[:id])
    redirect_back(fallback_location: root_path)
  end
  
  def remove
    place = Place.find(params[:id])
    if parent.modalities.joins(:spaces).where('spaces.place_id = ?', params[:id]).any?
      flash[:failure] = "Hay modalidades del evento que están usando esta categoría y no se puede eliminar"
    else
      parent.places.destroy(place)
    end
    
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    place = Place.find(params[:id])
    if place.spaces.any? 
      flash[:failure] = "Hay Modalidades de otros eventos que están usando esta categoría y no se puede eliminar"
    else
      place.destroy
    end
    redirect_back(fallback_location: root_path)
  end
  
  private

    def place_params
      params.require(:place).permit(:name)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.slim
= form_for [@event, @place] do |f|
  - if @back_url
    = hidden_field_tag :back_url, @back_url
  .row
    .col-lg-3
      = f.text_field :name, placeholder: "Nombre", class: "form-control"
    .col-lg-3
      = f.submit class: "btn btn-primary"

app/views/places/edit.html.slim
h1 Editar Categoría
br

== render 'form'

br
br
br
= link_to 'Volver', event_places_path, class: "btn btn-default"

app/views/places/index.html.slim
.page-header
  h1 Categorías
  == render 'form'
  br
  br
  .row
    .col-md-5.sm-12
      h3 Categorías del Evento
      table.table
        thead
          tr
            th Nombre
            th
        tbody
          - @own_places.each do |place|
            tr
              td = place.name
              td = link_to 'Sacar del Evento', remove_event_place_path(@event, place), class: "btn btn-danger btn-xs"
    
    .col-md-5.col-md-offset-1.sm-12
      h3 Todas las Categorías
      = paginate @places
      table.table
        thead
          tr
            th Nombre
            th
            th
      
        tbody
          - @places.each do |place|
            - if not @own_places.include?(place)
              tr
                td = place.name
                td.actions
                  = link_to 'Adicionar al Evento', assign_event_place_path(@event, place), class: "btn btn-primary btn-xs"
                  |&nbsp;
                  = link_to 'Editar', edit_event_place_path(@event, place), class: "btn btn-default btn-xs"
                  |&nbsp;
                  = link_to 'Eliminar', event_place_path(@event, place), method: :delete, data: {confirm: "Desea eliminar esta categoría?"}, class: "btn btn-danger btn-xs"
      
      = paginate @places
      
      br

app/views/places/new.html.slim
h1 New place

== render 'form'

= link_to 'Back', places_path

app/views/places/show.html.slim
p#notice = notice

p
  strong Name:
  = @place.name

= link_to 'Edit', edit_place_path(@place)
'|
= link_to 'Back', places_path